### ISSUE TITLE
ReSchema v3

### ISSUE THREAD

**Issue by vmarcosp** [rescriptbr/reschema#6]
## TODO
- [x] New schema API (#5).
- [x] New package on npm (from `reschema` to `@rescriptbr/reschema`).
- [x] Add a deprecation note on the old package. 
- [x] Update doc examples
- [x] API Reference for the new schema API
- [x] Release version
